<?php

/**
 * Auto-generated by CyphtContactsBridge::buildLibContent(). Do not edit;
*
 * @package modules
 * @subpackage dolibarr_contacts
 */

if (!defined('DEBUG_MODE')) { die(); }

/**
 * Read-only contact source backed by bridge/contacts.php in the Dolibarr
*
 * @subpackage dolibarr_contacts/lib
 */
class Hm_Dolibarr_Contacts {

    /** @var string Endpoint URL, injected via .env at build time */
    private $url;
    /** @var string Shared HMAC secret, same one the SSO login uses */
    private $secret;

    public function __construct() {
        /* Hm_Environment::get() rather than the env() helper, for the same
         * reason documented in the generated modules/site/lib.php. */
        $this->url = Hm_Environment::get('DOLIBARR_CONTACTS_URL', '');
        $this->secret = Hm_Environment::get('SSO_SHARED_SECRET', '');
    }

    /**
     * @return bool true if this source has everything it needs to run
     */
    public function configured() {
        return $this->url !== '' && $this->secret !== '';
    }

    /**
     * Seconds a fetched list stays good for. Dolibarr contacts change on a
    *
     * @return int
     */
    public function ttl() {
        return (int) Hm_Environment::get('DOLIBARR_CONTACTS_TTL', 300);
    }

    /**
     * The list Dolibarr published in the data directory.
     *
     * This class runs inside the Cypht app, which is a separate application
     * from Dolibarr with no $db, no $user and none of its functions. It gets
     * Dolibarr data either from a file Dolibarr wrote in advance, which is
     * this method, or by asking bridge/contacts.php over HTTP, which is
     * fetch() below. The file is preferred: an HTTP call needs the server to
     * reach its own public URL, which fails behind an auth proxy, an IP
     * allow list or an egress firewall.
     *
     * DOLIBARR_CACHE_DIR and DOLIBARR_MODULE_ROOT are both exported by
     * CyphtEnvBootstrap; the second is what lets this side load the naming
     * rules the writer uses, rather than restating them.
     *
     * @param string $login
     * @return array|false
     */
    private function fromCache($login) {
        $dir = Hm_Environment::get('DOLIBARR_CACHE_DIR', '');
        if ($dir === '') {
            return false;
        }

        $naming = Hm_Environment::get('DOLIBARR_MODULE_ROOT', '').'/class/integration/cachefiles.class.php';
        if (!is_readable($naming)) {
            Hm_Debug::add('dolibarr_contacts: cannot load '.$naming);
            return false;
        }
        require_once $naming;

        $file = CyphtCacheFiles::contactsFile($dir, $login);
        if (!is_readable($file)) {
            Hm_Debug::add('dolibarr_contacts: no cache file at '.$file);
            return false;
        }

        $data = json_decode((string) @file_get_contents($file), true);
        if (!is_array($data) || !isset($data['contacts']) || !is_array($data['contacts'])) {
            Hm_Debug::add('dolibarr_contacts: cache file unreadable or malformed');
            return false;
        }

        return $data['contacts'];
    }

    /**
     * Fetch the contact list for a Dolibarr login.
    *
     * @param string $login Dolibarr username, as put in the session by SSO
     * @return array|false Contact rows ready for Hm_Contact_Store::import(),
     */
    public function fetch($login) {
        $cached = $this->fromCache($login);
        if ($cached !== false) {
            return $cached;
        }

        if (!$this->configured()) {
            return false;
        }

        $timestamp = time();
        $signature = hash_hmac('sha256', $login.'|'.$timestamp.'|contacts', $this->secret);

        $url = $this->url.(strpos($this->url, '?') === false ? '?' : '&');
        $url .= http_build_query(array(
            'login' => $login,
            'token' => $timestamp.'.'.$signature,
        ));

        $body = $this->request($url);
        if ($body === false) {
            return false;
        }

        $data = json_decode($body, true);
        if (!is_array($data) || !array_key_exists('contacts', $data)) {
            Hm_Debug::add('dolibarr_contacts: unexpected response: '.substr($body, 0, 200));
            return false;
        }

        return $data['contacts'];
    }

    /**
     * @param string $url Fully built, signed request URL
     * @return string|false Response body, or false on transport failure
     */
    private function request($url) {
        $timeout = (int) Hm_Environment::get('DOLIBARR_CONTACTS_TIMEOUT', 5);

        if (function_exists('curl_init')) {
            $ch = curl_init($url);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
            curl_setopt($ch, CURLOPT_TIMEOUT, $timeout);
            curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, $timeout);
            /* The token is short lived but still a bearer credential, so
             * never follow a redirect that could carry it off-host. */
            curl_setopt($ch, CURLOPT_FOLLOWLOCATION, false);
            /* Some sites put HTTP auth in front of the whole Dolibarr. The
             * bridge does not need it, but the proxy answers 401 before the
             * request ever reaches PHP, so send it if one is configured. */
            $proxyAuth = Hm_Environment::get('DOLIBARR_BRIDGE_HTTP_AUTH', '');
            if ($proxyAuth !== '') {
                curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
                curl_setopt($ch, CURLOPT_USERPWD, $proxyAuth);
            }
            if (Hm_Environment::get('DOLIBARR_CONTACTS_INSECURE', 'false') === 'true') {
                /* For local XAMPP setups serving Dolibarr over a self-signed
                 * certificate. Off by default. */
                curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
                curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
            }
            $body = curl_exec($ch);
            $status = (int) curl_getinfo($ch, CURLINFO_HTTP_CODE);
            $err = curl_error($ch);
            curl_close($ch);

            if ($body === false || $status !== 200) {
                Hm_Debug::add('dolibarr_contacts: HTTP '.$status.' '.$err);
                return false;
            }
            return $body;
        }

        $streamOpts = array(
            'timeout' => $timeout,
            'follow_location' => 0,
            'ignore_errors' => true,
        );
        $proxyAuth = Hm_Environment::get('DOLIBARR_BRIDGE_HTTP_AUTH', '');
        if ($proxyAuth !== '') {
            $streamOpts['header'] = 'Authorization: Basic '.base64_encode($proxyAuth)."\r\n";
        }
        $context = stream_context_create(array('http' => $streamOpts));
        $body = @file_get_contents($url, false, $context);
        if ($body === false) {
            Hm_Debug::add('dolibarr_contacts: request failed, no curl and file_get_contents returned false');
            return false;
        }
        return $body;
    }
}
