<?php

/**
 * Auto-generated by CyphtContactsBridge::buildModulesContent(). Do not edit;
*
 * @package modules
 * @subpackage dolibarr_contacts
 */

if (!defined('DEBUG_MODE')) { die(); }

require_once APP_PATH.'modules/dolibarr_contacts/hm-dolibarr-contacts.php';

/**
 * Pulls Dolibarr third parties and contacts into the contact store.
*
 * @subpackage dolibarr_contacts/handler
 */
class Hm_Handler_load_dolibarr_contacts extends Hm_Handler_Module {

    public function process() {
        $store = $this->get('contact_store');
        if (!$store) {
            return;
        }

        $login = $this->session->get('username', false);
        if (!$login) {
            return;
        }

        $source = new Hm_Dolibarr_Contacts();
        if (!$source->configured()) {
            $this->out('dolibarr_contacts_status', 'unconfigured');
            return;
        }

        $status = 'ok';

        /* Every page load would otherwise mean an HTTP round trip to
         * Dolibarr, including each autocomplete keystroke. Cache the
         * fetched list in the Cypht session for a short TTL instead. */
        $cache = $this->session->get('dolibarr_contacts_cache', false);
        $stamp = (int) $this->session->get('dolibarr_contacts_cache_at', 0);

        if (!is_array($cache) || (time() - $stamp) > $source->ttl()) {
            $fetched = $source->fetch($login);
            if ($fetched === false) {
                /* Fetch failed. Keep serving the stale list rather than
                 * blanking the address book mid-session; the reason is on
                 * the debug log. */
                $status = 'error';
                if (!is_array($cache)) {
                    $cache = array();
                }
            } else {
                $cache = $fetched;
                $this->session->set('dolibarr_contacts_cache', $cache);
                $this->session->set('dolibarr_contacts_cache_at', time());
            }
        }

        if (count($cache) > 0) {
            $store->import($cache);
        }

        $this->append('contact_sources', 'dolibarr');
        $this->out('contact_store', $store, false);
        $this->out('dolibarr_contact_count', count($cache));
        $this->out('dolibarr_contacts_status', $status);
    }
}

/**
 * Explains an empty Dolibarr address book, above the category tabs.
*
 * @subpackage dolibarr_contacts/output
 */
class Hm_Output_dolibarr_contacts_notice extends Hm_Output_Module {

    protected function output() {
        $status = $this->get('dolibarr_contacts_status', 'unconfigured');
        $count = (int) $this->get('dolibarr_contact_count', 0);

        if ($status === 'ok' && $count > 0) {
            return ''; /* contacts loaded, nothing to explain */
        }

        if ($status === 'unconfigured') {
            return $this->notice(
                'warning',
                'Dolibarr contacts are not configured',
                'The webmail module could not find its link back to Dolibarr. '.
                'Re-run Generate in the module setup page to rebuild the configuration.',
                ''
            );
        }

        if ($status === 'error') {
            return $this->notice(
                'danger',
                'Could not reach Dolibarr',
                'Your Dolibarr contacts could not be loaded, so this list may be '.
                'incomplete. This is a connection problem, not an empty address book'.
                'Ask your administrator'.
                'to check the webmail module setup.',
                ''
            );
        }

        $newUrl = Hm_Environment::get('DOLIBARR_NEW_CONTACT_URL', '');

        return $this->notice(
            'info',
            'No Dolibarr contacts yet',
            'This address book is filled automatically from Dolibarr, so there is '.
            'nothing to add here directly. Create a contact in Dolibarr and it will '.
            'appear on this page. A contact needs an email address to show up, and '.
            'new entries can take up to five minutes to arrive.',
            $newUrl
        );
    }

    /**
     * @param string $level  Bootstrap alert suffix: info, warning, danger
     * @param string $title  Short headline
     * @param string $body   Explanatory sentence(s)
     * @param string $url    Optional Dolibarr URL for a call to action
     * @return string
     */
    private function notice($level, $title, $body, $url) {
        $res = '<div class="alert alert-'.$this->html_safe($level).' mx-3 my-2" role="alert">';
        $res .= '<h6 class="alert-heading mb-1">'.$this->html_safe($this->trans($title)).'</h6>';
        $res .= '<p class="mb-0 small">'.$this->html_safe($this->trans($body)).'</p>';

        if ($url !== '') {
            /* target="_top" because Cypht is embedded in an iframe inside
             * Dolibarr; without it the Dolibarr page would open nested
             * inside the webmail pane. */
            $res .= '<hr class="my-2">';
            $res .= '<a class="btn btn-sm btn-primary" target="_top" href="'.$this->html_safe($url).'">';
            $res .= '<i class="bi bi-person-plus-fill"></i> '.$this->html_safe($this->trans('Add a contact in Dolibarr'));
            $res .= '</a>';
        }

        $res .= '</div>';

        return $res;
    }
}
