<?php

/**
 * Auto-generated by CyphtContactsBridge::buildSetupContent(). Do not edit;
*
 * @package modules
 * @subpackage dolibarr_contacts
 */

if (!defined('DEBUG_MODE')) { die(); }

handler_source('dolibarr_contacts');
output_source('dolibarr_contacts');

/* Contacts page: the full list, grouped by third party. */
add_handler('contacts', 'load_dolibarr_contacts', true, 'dolibarr_contacts', 'load_contacts', 'after');

/* Compose: To/Cc/Bcc autocomplete reads the store via ajax_autocomplete_contact. */
add_handler('compose', 'load_dolibarr_contacts', true, 'dolibarr_contacts', 'load_contacts', 'after');
add_handler('ajax_autocomplete_contact', 'load_dolibarr_contacts', true, 'dolibarr_contacts', 'load_contacts', 'after');

/* Message view: lets find_message_contacts recognise senders we know about,
 * so a Dolibarr contact is not offered as "add to contacts". */
add_handler('ajax_imap_message_content', 'load_dolibarr_contacts', true, 'dolibarr_contacts', 'load_contacts', 'after');

/* vCard export includes the Dolibarr source too. */
add_handler('export_contact', 'load_dolibarr_contacts', true, 'dolibarr_contacts', 'process_export_contacts', 'before');

/* Empty/error state, rendered above the category tabs. Cypht's own
 * "No contacts in this category" is per tab and says nothing about where
 * contacts are supposed to come from. */
add_output('contacts', 'dolibarr_contacts_notice', true, 'dolibarr_contacts', 'contacts_content_start', 'after');

return array(
    'allowed_output' => array(
        'dolibarr_contact_count' => array(FILTER_VALIDATE_INT, false),
        'dolibarr_contacts_status' => array(FILTER_SANITIZE_FULL_SPECIAL_CHARS, false),
    ),
);
