<?php
/* Copyright (C) 2026  Camile   <camilevahviraki@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

require_once __DIR__ . '/../state/cyphtinstallstate.class.php';

/**
 * \file        class/sso/cyphtssobridge.class.php
 * \ingroup     cyphtWebmail
 * \brief       Dolibarr -> Cypht single sign-on bridge. Extracted out of
 *              CyphtManager, which had grown too large - see
 *              class/cyphtmanager.class.php for the facade that wires this
 *              together with its siblings.
 *
 * Owns the shared HMAC secret, the short-lived login tokens derived from
 * it, the generated modules/site/lib.php override (Custom_Auth/
 * Custom_Session) that makes Cypht trust those tokens instead of a real
 * IMAP/DB backend, and the actual in-process "functional login" call.
 */
class CyphtSsoBridge
{
	/**
	 * @var DoliDB
	 */
	public $db;

	/**
	 * @var string  Last error message, if any call returned false/failure.
	 */
	public $error = '';

	/**
	 * @var CyphtInstallState
	 */
	private $paths;

	/**
	 * @param DoliDB $db Database handler
	 * @param CyphtInstallState $paths
	 */
	public function __construct($db, CyphtInstallState $paths)
	{
		$this->db = $db;
		$this->paths = $paths;
	}

	/**
	 * Shared secret used to sign the short-lived SSO tokens passed to
	 * Cypht's cypht_login() in place of a real mailbox password (see
	 * generateSsoLoginToken() and buildSiteAuthOverrideContent()). Generated
	 * once and persisted in llx_const so it survives across requests and
	 * rebuilds; the same value is written into Cypht's own .env so
	 * Custom_Auth::check_credentials() can verify against it.
	 *
	 * @return string
	 */
	public function getOrCreateSsoSecret()
	{
		global $conf;

		$secret = getDolGlobalString('CYPHTWEBMAIL_SSO_SECRET', '');
		if ($secret !== '') {
			return $secret;
		}

		$secret = bin2hex(random_bytes(32));
		dolibarr_set_const($this->db, 'CYPHTWEBMAIL_SSO_SECRET', $secret, 'chaine', 0, '', $conf->entity);

		return $secret;
	}

	/**
	 * Build a short-lived, single-purpose token proving "this is really
	 * the current Dolibarr user", to hand to Cypht's cypht_login() as the
	 * password argument. It is never a real mailbox credential - just an
	 * HMAC of the username + timestamp, verified by Custom_Auth in
	 * modules/site/lib.php against the same SSO_SHARED_SECRET. The 60s
	 * window keeps a captured token from being replayable indefinitely.
	 *
	 * @param string $login Dolibarr username to embed in the token
	 * @return string
	 */
	public function generateSsoLoginToken($login)
	{
		$secret = $this->getOrCreateSsoSecret();
		$timestamp = time();
		$signature = hash_hmac('sha256', $login . '|' . $timestamp, $secret);

		return $timestamp . '.' . $signature;
	}

	/**
	 * Source for the generated modules/site/lib.php override that makes
	 * AUTH_TYPE=custom authenticate against our SSO token instead of a
	 * real IMAP/DB backend. Regenerated on every build (same pattern as
	 * CyphtVendorBridge::ensureCyphtVendorBridge()'s autoload shim) rather
	 * than hand-edited in vendor/, so a "composer update" never silently
	 * reverts it.
	 *
	 * @return string
	 */
	private function buildSiteAuthOverrideContent()
	{
		return <<<'PHP'
<?php

/**
 * Auto-generated by CyphtSsoBridge::buildSiteAuthOverrideContent() - do not
 * edit, this file is recreated on every build and any manual changes will be
 * lost. See class/sso/cyphtssobridge.class.php in the cyphtWebmail module
 * for the source of truth.
 *
 * Implements Dolibarr SSO: AUTH_TYPE=custom hands credential checking to
 * Custom_Auth below instead of a real IMAP/DB backend. The "password"
 * Custom_Auth ever sees is a short-lived HMAC token generated by
 * CyphtSsoBridge::generateSsoLoginToken() for the *currently logged in
 * Dolibarr user* - never a real mailbox password. Once logged in this
 * way, each user adds their actual IMAP mailbox separately via Cypht's
 * own Servers/Accounts settings page, exactly as Tiki's integration does.
 *
 * SESSION_TYPE=custom activates Custom_Session below, which stores
 * session data in its own encrypted files rather than PHP's native
 * session_start()/$_SESSION - required because performSsoLogin() runs
 * in the same PHP request as Dolibarr's own already-active session, and
 * Cypht's stock "PHP" session type would collide with it (documented at
 * https://github.com/cypht-org/cypht/wiki/Integration-Options).
 *
 * @package modules
 * @subpackage site
 */
class Custom_Session extends Hm_Session {

    use Hm_Session_Auth;

    /** @var bool true once a new login has established data to persist */
    private $existing = false;

    private function session_dir() {
        // Hm_Environment::get() reads array_merge($_ENV, $_SERVER) - real
        // per-request PHP superglobals. The global env() helper instead
        // does getenv() ?: default, which reads the *process-wide* OS
        // environment table populated via putenv() (Hm_Environment::load()
        // turns on Symfony Dotenv's usePutenv(true)). Symfony's own source
        // warns "putenv() is not thread safe" - and on Windows, Apache's
        // mpm_winnt runs one process with many threads sharing that same
        // process-wide table, so a concurrent request's putenv() unset/set
        // pair (Dotenv unsets a key before resetting it) can be observed
        // mid-flight by another thread's getenv() call. That's what was
        // causing this to intermittently fall back to sys_get_temp_dir()
        // instead of the real USER_SETTINGS_DIR on some requests - Cypht
        // then looked in the wrong directory, found no session file,
        // reported "inactive", and the client force-reloaded (see
        // public/site.js's logout()-on-!router_login_state). $_ENV itself
        // is set unconditionally by Dotenv::populate() regardless of the
        // putenv race (see vendor/symfony/dotenv/Dotenv.php), so reading
        // it directly via Hm_Environment::get() sidesteps the race.
        $base = dirname(rtrim(Hm_Environment::get('USER_SETTINGS_DIR', sys_get_temp_dir()), '/\\'));
        $dir = $base.'/sso_sessions';
        if (!is_dir($dir)) {
            @mkdir($dir, 0700, true);
        }
        return $dir;
    }

    private function session_file($key) {
        return $this->session_dir().'/'.preg_replace('/[^a-f0-9]/', '', (string) $key).'.session';
    }

    /**
     * Temporary diagnostic log, separate from Cypht's own debug system
     * (which is a black box from Dolibarr's side) - tracks this specific
     * request's method/URI plus each locking step, so a hung/crashed
     * request can be pinned to an exact line even though it returns a
     * raw 503 with no catchable PHP error at all.
     */
    private function dbg($line) {
        $uri = isset($_SERVER['REQUEST_URI']) ? $_SERVER['REQUEST_URI'] : '?';
        $method = isset($_SERVER['REQUEST_METHOD']) ? $_SERVER['REQUEST_METHOD'] : '?';
        // Written under the module root itself (not USER_SETTINGS_DIR,
        // which lives under Dolibarr's separate documents root) so this
        // is directly readable without needing anyone to relay it.
        $logPath = dirname(rtrim(APP_PATH, '/\\'), 3) . '/session_debug.log';
        @file_put_contents(
            $logPath,
            sprintf("[%s] pid=%d %s %s key=%s :: %s\n", date('H:i:s.u'), getmypid(), $method, $uri, substr((string) $this->session_key, 0, 8), $line),
            FILE_APPEND
        );
    }

    public function check($request, $user = false, $pass = false, $fingerprint = true) {
        if ($user !== false && $pass !== false) {
            if ($this->auth($user, $pass)) {
                $this->set_key($request);
                $this->session_key = bin2hex(random_bytes(16));
                $this->loaded = true;
                $this->data = [];
                $this->active = true;
                $this->dbg('NEW LOGIN established');
                if ($fingerprint) {
                    $this->set_fingerprint($request);
                } else {
                    $this->set('fingerprint', '');
                }
                $this->save_auth_detail();
                $this->just_started();
            } else {
                $this->dbg('auth() returned false for new login attempt');
            }
        } elseif (array_key_exists($this->cname, $request->cookie)) {
            $this->session_key = $request->cookie[$this->cname];
            $this->dbg('checking existing session cookie');
            $this->get_key($request);
            $this->existing = true;
            $this->start($request, true);
            if ($this->active) {
                $this->check_fingerprint($request);
                $this->dbg('active after fingerprint check = '.($this->active ? 'yes' : 'no'));
            }
        } else {
            $this->dbg('no cookie, no user/pass - anonymous request');
        }
        return $this->is_active();
    }

    public function start($request, $existing_session = false) {
        if (!$existing_session) {
            return;
        }
        $file = $this->session_file($this->session_key);
        $this->dbg('start(): about to check is_readable on '.$file);
        if (!is_readable($file)) {
            $this->active = false;
            $this->dbg('start(): file not readable, marking inactive');
            return;
        }
        // Locked read: Cypht's own JS fires several AJAX calls back to back
        // on page load, each a separate PHP request reading/writing this
        // same file. Without a lock, a read racing an in-progress write
        // (from another of those parallel requests) can return a partial
        // write, fail to decrypt, and report the session as inactive -
        // which is exactly what was causing repeated client-side reloads
        // (Cypht's JS force-reloads whenever it sees a logged-out response).
        $fh = @fopen($file, 'rb');
        if ($fh === false) {
            $this->active = false;
            $this->dbg('start(): fopen failed');
            return;
        }
        $this->dbg('start(): fopen ok, requesting LOCK_SH');
        flock($fh, LOCK_SH);
        $this->dbg('start(): LOCK_SH acquired, reading');
        $raw = stream_get_contents($fh);
        flock($fh, LOCK_UN);
        fclose($fh);
        $this->dbg('start(): read '.strlen($raw).' bytes, unlocked');

        $data = $this->plaintext($raw);
        if (is_array($data)) {
            $this->data = $data;
            $this->active = true;
            $this->dbg('start(): decrypt OK, session active');
        } else {
            $this->active = false;
            $this->dbg('start(): decrypt FAILED (raw len '.strlen($raw).'), session inactive');
        }
    }

    public function get($name, $default = false, $user = false) {
        if ($user) {
            return (array_key_exists('user_data', $this->data) && array_key_exists($name, $this->data['user_data']))
                ? $this->data['user_data'][$name] : $default;
        }
        return array_key_exists($name, $this->data) ? $this->data[$name] : $default;
    }

    public function set($name, $value, $user = false) {
        if ($user) {
            $this->data['user_data'][$name] = $value;
        } else {
            $this->data[$name] = $value;
        }
    }

    public function del($name) {
        if (array_key_exists($name, $this->data)) {
            unset($this->data[$name]);
            return true;
        }
        return false;
    }

    public function end() {
        if ($this->active && !$this->session_closed) {
            $this->dbg('end(): persisting via write_locked()');
            $this->write_locked();
        }
        $this->active = false;
    }

    /**
     * Write session data to avoid locking, keep session active, but
     * don't allow further writes - called by several core/module
     * handlers (nux's "Add an E-mail Account" flow among them, plus
     * imap_folders, sievefilters, 2fa, github, wordpress) before a slow
     * operation (e.g. testing IMAP/SMTP credentials) so this session's
     * file lock isn't held for the duration. Every stock Cypht session
     * backend (Hm_PHP_Session, Hm_DB_Session, Hm_Memcached_Session)
     * implements this; Hm_Session itself (which Custom_Session extends)
     * declares $session_closed but provides no default close_early() -
     * leaving it unimplemented here meant a hard "Call to undefined
     * method Custom_Session::close_early()" fatal (an uncaught Error ->
     * 503, no catchable PHP error and no JSON the client could parse)
     * the instant any of those modules ran. That's exactly why "Add an
     * E-mail Account" worked in a standalone Cypht install (using a
     * stock session backend) but failed here.
     */
    public function close_early() {
        if ($this->active && !$this->session_closed) {
            $this->dbg('close_early(): persisting via write_locked()');
            $this->write_locked();
        }
        $this->session_closed = true;
    }

    private function write_locked() {
        // Locked write, same reasoning as start() above - exclusive
        // lock so a concurrent request's read can't observe a
        // half-written file.
        $fh = @fopen($this->session_file($this->session_key), 'cb');
        if ($fh !== false) {
            flock($fh, LOCK_EX);
            $this->dbg('write_locked(): LOCK_EX acquired, writing');
            ftruncate($fh, 0);
            rewind($fh);
            fwrite($fh, $this->ciphertext($this->data));
            fflush($fh);
            flock($fh, LOCK_UN);
            fclose($fh);
            $this->dbg('write_locked(): write complete, unlocked');
        } else {
            $this->dbg('write_locked(): fopen failed');
        }
    }

    public function destroy($request) {
        @unlink($this->session_file($this->session_key));
        $this->delete_cookie($request, $this->cname);
        $this->delete_cookie($request, 'hm_id');
        $this->active = false;
    }
}

class Custom_Auth extends Hm_Auth_DB {

    /**
     * @param string $user username (the Dolibarr login)
     * @param string $pass "{timestamp}.{hmac}" token from
     *                      CyphtSsoBridge::generateSsoLoginToken(), not a
     *                      real password
     * @return bool true if the token is a valid, fresh SSO assertion
     */
    public function check_credentials($user, $pass) {
        // See the comment in Custom_Session::session_dir() above - the
        // global env() helper reads the process-wide (not thread-safe)
        // putenv() table, so it must be avoided here too.
        $secret = Hm_Environment::get('SSO_SHARED_SECRET', '');
        if ($secret === '' || strpos($pass, '.') === false) {
            return false;
        }

        list($timestamp, $signature) = explode('.', $pass, 2);
        if (!ctype_digit($timestamp)) {
            return false;
        }

        // Anti-replay window: a captured token is only valid for a minute.
        if (abs(time() - (int) $timestamp) > 60) {
            return false;
        }

        $expected = hash_hmac('sha256', $user.'|'.$timestamp, $secret);

        return hash_equals($expected, $signature);
    }
}

/**
 * Replaces Hm_User_Config_File as the user-settings backend (activated via
 * USER_CONFIG_TYPE=custom:Custom_User_Config in .env, a hook Cypht's own
 * lib/config.php:load_user_config_object() provides for exactly this).
 *
 * Root cause this fixes: Hm_User_Config_File encrypts/decrypts the saved
 * settings file using the "password" argument passed to load()/save() as
 * the literal encryption key (see Hm_Crypt::ciphertext()/plaintext() in
 * lib/config.php). Every one of our SSO logins passes a freshly generated,
 * per-request HMAC token (CyphtSsoBridge::generateSsoLoginToken()) as that
 * password - a *different* key on every page load - so anything encrypted
 * with last request's key can never be decrypted with this request's key.
 * Settings and IMAP/SMTP servers silently vanish and every load() falls
 * back to defaults. That's the entire "nothing persists after reload" bug.
 *
 * Tiki's own Cypht integration (lib/cypht/integration/classes.php,
 * Tiki_Hm_User_Config) hits this identical problem and solves it the same
 * way: subclass Hm_Config directly, ignore the $key parameter completely,
 * and store settings through the host CMS's own persistence instead of
 * Cypht's password-derived encryption. Tiki uses its own DB preference
 * table (TikiLib::lib('tiki')->get/set_user_preference()); we don't have
 * that abstraction, so this stores plain (unencrypted) JSON per user under
 * USER_SETTINGS_DIR instead - same principle, file-based backend to match
 * our existing USER_CONFIG_TYPE=file layout. Since Dolibarr's own
 * authentication already gates who can reach this page at all, there is
 * no meaningful secret being protected by encrypting these files anyway.
 *
 * @package modules
 * @subpackage site
 */
class Custom_User_Config extends Hm_Config {

    /** @var object Hm_Site_Config_File-like site config */
    private $site_config;

    /** @var string current username, set on load()/reload() */
    private $username;

    public function __construct($config) {
        $this->site_config = $config;
        $this->config = array_merge($this->config, $config->user_defaults);
    }

    private function get_path($username) {
        $dir = $this->site_config->get('user_settings_dir', false);
        $safe = preg_replace('/[^a-zA-Z0-9_.@-]/', '_', (string) $username);
        return rtrim((string) $dir, '/\\').'/'.$safe.'.json';
    }

    /**
     * @param string $username username
     * @param string $key intentionally ignored - see class doc comment
     */
    public function load($username, $key = null) {
        $this->username = $username;
        $source = $this->get_path($username);
        if (is_readable($source)) {
            $str_data = file_get_contents($source);
            if ($str_data) {
                $data = $this->decode($str_data);
                if (is_array($data)) {
                    $this->config = array_merge($this->config, $data);
                    $this->set_tz();
                }
            }
        }
    }

    public function reload($data, $username = false) {
        $this->username = $username;
        $this->config = $data;
        $this->set_tz();
    }

    /**
     * @param string $username username
     * @param string $key intentionally ignored - see class doc comment
     */
    public function save($username, $key = null) {
        $this->shuffle();
        $removed = $this->filter_servers();

        $dir = $this->site_config->get('user_settings_dir', false);
        if ($dir && !is_dir($dir)) {
            @mkdir($dir, 0700, true);
        }

        $fh = @fopen($this->get_path($username), 'cb');
        if ($fh !== false) {
            flock($fh, LOCK_EX);
            ftruncate($fh, 0);
            rewind($fh);
            fwrite($fh, json_encode($this->config));
            fflush($fh);
            flock($fh, LOCK_UN);
            fclose($fh);
            @chmod($this->get_path($username), 0600);
        }

        $this->restore_servers($removed);
    }
}
PHP;
	}

	/**
	 * Write the generated Custom_Auth/Custom_Session override to Cypht's
	 * modules/site/lib.php. Must run on every build, same reasoning as
	 * CyphtVendorBridge::ensureCyphtVendorBridge(): Composer fully
	 * re-extracts a package directory whenever its locked version changes,
	 * which would silently wipe this out.
	 *
	 * @return bool
	 */
	public function writeSiteAuthOverride()
	{
		$path = $this->paths->getCyphtPath() . '/modules/site/lib.php';

		if (file_put_contents($path, $this->buildSiteAuthOverrideContent()) === false) {
			$this->error = 'Could not write ' . $path;
			return false;
		}

		return true;
	}

	/**
	 * Log the given Dolibarr user into Cypht via its official "functional
	 * login" integration option (same-subdomain SSO, see
	 * https://github.com/cypht-org/cypht/wiki/API-Login) - calls
	 * cypht_login() directly in-process instead of round-tripping through
	 * an HTTP POST, setting the hm_id/hm_session cookies on the current
	 * response. Must be called before any HTML output.
	 *
	 * Skips the actual login call entirely if this browser already holds a
	 * live Cypht session for this exact user (see hasLiveSsoSession()).
	 * This matters because cyphtWebmailindex.php (the outer Dolibarr page
	 * that embeds Cypht in an iframe) calls this on *every* page load -
	 * every browser refresh or re-click of the CyphtWebmail menu item, not
	 * just the first visit. cypht_login() always takes Custom_Session's
	 * "new login" branch, which unconditionally does $this->data = [] -
	 * wiping the session. Cypht itself only mirrors settings changes made
	 * during a session into that same session data (see
	 * Hm_Handler_save_user_data in modules/core/handler_modules.php,
	 * explicitly commented "session only" in Cypht's own source) and only
	 * ever writes them to permanent storage via a couple of narrow
	 * triggers (re-entering your password via "Save and Logout", or an
	 * IMAP folder change flagging save_on_login) - so unconditionally
	 * logging in fresh on every outer-page reload was silently discarding
	 * everything that hadn't hit one of those triggers, which in practice
	 * was almost everything: general settings, IMAP/SMTP servers added
	 * but not yet flagged for save-on-login, etc. That's the actual
	 * mechanism behind "nothing persists after reload" - a distinct,
	 * additional cause from the user-config encryption-key mismatch fixed
	 * by Custom_User_Config above. Requests made *inside* the iframe
	 * (talking to public/index.php directly, e.g. every settings save or
	 * folder click) never hit this - they reuse the existing session
	 * cookie fine, which is why a change could look "saved" right up
	 * until the next full reload of the outer page.
	 *
	 * @param string $login Dolibarr username to log into Cypht as
	 * @param string $cyphtUrl URL of the published Cypht app - does not
	 *                          need to be absolute already, see below
	 * @return bool true if Cypht accepted the SSO token, or a live session
	 *              already existed and was left alone
	 */
	public function performSsoLogin($login, $cyphtUrl)
	{
		if ($this->hasLiveSsoSession($login)) {
			return true;
		}

		$apiFile = $this->paths->getCyphtPath() . '/modules/api_login/api.php';
		if (!is_readable($apiFile)) {
			$this->error = 'modules/api_login/api.php not found - was the "api_login" module built into CYPHT_MODULES?';
			return false;
		}

		require_once $apiFile;

		$token = $this->generateSsoLoginToken($login);

		$ok = cypht_login($login, $token, $this->absolutizeUrl($cyphtUrl));
		if ($ok) {
			$this->rememberSsoSession($login);
		}

		return $ok;
	}

	/**
	 * Name of the cookie we set ourselves (separate from Cypht's own
	 * hm_session/hm_id) recording which Dolibarr login the current Cypht
	 * session belongs to, so a later request can tell "already logged in
	 * as this user" apart from "already logged in as someone else" or
	 * "never logged in" without decrypting anything.
	 *
	 * @return string
	 */
	private function ssoUserCookieName()
	{
		return 'cyphtwebmail_ssouser';
	}

	/**
	 * True if this browser already presents a plausible, still-on-disk
	 * Cypht session for $login - i.e. calling cypht_login() again would
	 * only destroy perfectly good session state for no benefit. Checks
	 * three things, all required: our own cookie recording which login
	 * the session belongs to (matches $login), Cypht's own hm_session
	 * cookie (the session key), and that the session file it names still
	 * actually exists on disk (an expired/cleaned-up/never-written
	 * session must fall through to a real login instead of leaving the
	 * user stuck against a dead session).
	 *
	 * @param string $login
	 * @return bool
	 */
	private function hasLiveSsoSession($login)
	{
		if (empty($_COOKIE['hm_session']) || empty($_COOKIE['hm_id']) || empty($_COOKIE[$this->ssoUserCookieName()])) {
			return false;
		}

		if (!hash_equals((string) $login, (string) $_COOKIE[$this->ssoUserCookieName()])) {
			return false;
		}

		$sessionKey = preg_replace('/[^a-f0-9]/', '', (string) $_COOKIE['hm_session']);
		if ($sessionKey === '') {
			return false;
		}

		// Mirrors Custom_Session::session_file()'s own naming convention in
		// the generated modules/site/lib.php (see
		// buildSiteAuthOverrideContent() above) - dataDir/sso_sessions/<key>.session.
		$sessionFile = $this->paths->getDataDir() . '/sso_sessions/' . $sessionKey . '.session';

		return is_readable($sessionFile);
	}

	/**
	 * Record which Dolibarr login the session cypht_login() just
	 * established belongs to, so the next request's hasLiveSsoSession()
	 * check can recognize it. Session-lifetime cookie (no explicit
	 * expiry) - deliberately no longer-lived than that, since it is only
	 * ever meant to skip a redundant re-login within the same browser
	 * session, not to authenticate anything itself.
	 *
	 * @param string $login
	 * @return void
	 */
	private function rememberSsoSession($login)
	{
		$secure = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off');
		setcookie($this->ssoUserCookieName(), $login, array(
			'path' => '/',
			'secure' => $secure,
			'httponly' => true,
			'samesite' => 'Lax',
		));
	}

	/**
	 * cypht_login()'s own url_parse() does parse_url($url)['scheme'/'host']
	 * with no fallback, to work out the cookie domain/secure flag - it
	 * needs a real absolute URL. dol_buildpath(..., 1) does not reliably
	 * return one (can come back host-relative depending on Dolibarr's own
	 * config), which is what caused "Undefined array key scheme/host"
	 * warnings here. Prepends the current request's own scheme+host if
	 * $url doesn't already have one; already-absolute URLs pass through.
	 *
	 * @param string $url
	 * @return string
	 */
	private function absolutizeUrl($url)
	{
		if (preg_match('#^https?://#i', $url)) {
			return $url;
		}

		$scheme = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
		$host = !empty($_SERVER['HTTP_HOST']) ? $_SERVER['HTTP_HOST'] : 'localhost';
		$path = (substr($url, 0, 1) === '/') ? $url : '/' . $url;

		return $scheme . '://' . $host . $path;
	}
}
