<?php
/* Copyright (C) 2026  Camile   <camilevahviraki@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

require_once __DIR__ . '/../state/cyphtinstallstate.class.php';

/**
 * \file        class/sso/cyphtssobridge.class.php
 * \ingroup     cyphtWebmail
 * \brief       Dolibarr -> Cypht single sign-on bridge. Owns the shared
 *              HMAC secret, short-lived login tokens, the generated
 *              modules/site/lib.php auth override, and the in-process
 *              "functional login" call.
 */
class CyphtSsoBridge
{
	/**
	 * @var DoliDB
	 */
	public $db;

	/**
	 * @var string  Last error message, if any call returned false/failure.
	 */
	public $error = '';

	/**
	 * @var CyphtInstallState
	 */
	private $paths;

	/**
	 * @param DoliDB $db Database handler
	 * @param CyphtInstallState $paths
	 */
	public function __construct($db, CyphtInstallState $paths)
	{
		$this->db = $db;
		$this->paths = $paths;
	}

	/**
	 * Secret signing the short-lived SSO tokens (see generateSsoLoginToken()).
	 * Persisted in llx_const and mirrored into Cypht's .env so
	 * Custom_Auth::check_credentials() can verify against it.
	 *
	 * @return string
	 */
	public function getOrCreateSsoSecret()
	{
		global $conf;

		$secret = getDolGlobalString('CYPHTWEBMAIL_SSO_SECRET', '');
		if ($secret !== '') {
			return $secret;
		}

		$secret = bin2hex(random_bytes(32));
		dolibarr_set_const($this->db, 'CYPHTWEBMAIL_SSO_SECRET', $secret, 'chaine', 0, '', $conf->entity);

		return $secret;
	}

	/**
	 * HMAC token proving "this is really the current Dolibarr user", passed
	 * to Cypht's cypht_login() as the password. Never a real mailbox
	 * credential. Valid for 60s to limit replay.
	 *
	 * @param string $login Dolibarr username to embed in the token
	 * @return string
	 */
	public function generateSsoLoginToken($login)
	{
		$secret = $this->getOrCreateSsoSecret();
		$timestamp = time();
		$signature = hash_hmac('sha256', $login . '|' . $timestamp, $secret);

		return $timestamp . '.' . $signature;
	}

	/**
	 * Source for the generated modules/site/lib.php auth override.
	 * Regenerated on every build rather than hand-edited in vendor/, so a
	 * "composer update" never silently reverts it.
	 *
	 * @return string
	 */
	private function buildSiteAuthOverrideContent()
	{
		return <<<'PHP'
<?php

/**
 * Auto-generated by CyphtSsoBridge::buildSiteAuthOverrideContent(). Do not
 * edit; recreated on every build. See class/sso/cyphtssobridge.class.php.
 *
 * AUTH_TYPE=custom routes credential checking to Custom_Auth below, using
 * a short-lived HMAC token instead of a real mailbox password.
 *
 * SESSION_TYPE=custom activates Custom_Session below, storing session data
 * in its own files rather than PHP's native session_start()/$_SESSION,
 * since performSsoLogin() runs inside Dolibarr's own already-active
 * session and Cypht's stock "PHP" session type would collide with it.
 *
 * @package modules
 * @subpackage site
 */
class Custom_Session extends Hm_Session {

    use Hm_Session_Auth;

    /** @var bool true once a new login has established data to persist */
    private $existing = false;

    private function session_dir() {
        // Hm_Environment::get() reads $_ENV directly. The global env()
        // helper instead reads getenv(), backed by a process-wide table
        // that putenv() is not thread-safe for; on Windows (Apache
        // mpm_winnt, one process/many threads) a concurrent request could
        // observe it mid-update and fall back to the wrong directory.
        $base = dirname(rtrim(Hm_Environment::get('USER_SETTINGS_DIR', sys_get_temp_dir()), '/\\'));
        $dir = $base.'/sso_sessions';
        if (!is_dir($dir)) {
            @mkdir($dir, 0700, true);
        }
        return $dir;
    }

    private function session_file($key) {
        return $this->session_dir().'/'.preg_replace('/[^a-f0-9]/', '', (string) $key).'.session';
    }

    /**
     * Diagnostic log for pinning a hung/crashed request to an exact line
     * even when it returns a raw 503 with no catchable PHP error.
     */
    private function dbg($line) {
        $uri = isset($_SERVER['REQUEST_URI']) ? $_SERVER['REQUEST_URI'] : '?';
        $method = isset($_SERVER['REQUEST_METHOD']) ? $_SERVER['REQUEST_METHOD'] : '?';
        // Written under the module root, not USER_SETTINGS_DIR, so it's
        // directly reachable on disk.
        $logPath = dirname(rtrim(APP_PATH, '/\\'), 3) . '/session_debug.log';
        @file_put_contents(
            $logPath,
            sprintf("[%s] pid=%d %s %s key=%s :: %s\n", date('H:i:s.u'), getmypid(), $method, $uri, substr((string) $this->session_key, 0, 8), $line),
            FILE_APPEND
        );
    }

    public function check($request, $user = false, $pass = false, $fingerprint = true) {
        if ($user !== false && $pass !== false) {
            if ($this->auth($user, $pass)) {
                $this->set_key($request);
                $this->session_key = bin2hex(random_bytes(16));
                $this->loaded = true;
                $this->data = [];
                $this->active = true;
                $this->dbg('NEW LOGIN established');
                if ($fingerprint) {
                    $this->set_fingerprint($request);
                } else {
                    $this->set('fingerprint', '');
                }
                $this->save_auth_detail();
                $this->just_started();
            } else {
                $this->dbg('auth() returned false for new login attempt');
            }
        } elseif (array_key_exists($this->cname, $request->cookie)) {
            $this->session_key = $request->cookie[$this->cname];
            $this->dbg('checking existing session cookie');
            $this->get_key($request);
            $this->existing = true;
            $this->start($request, true);
            if ($this->active) {
                $this->check_fingerprint($request);
                $this->dbg('active after fingerprint check = '.($this->active ? 'yes' : 'no'));
            }
        } else {
            $this->dbg('no cookie, no user/pass; anonymous request');
        }
        return $this->is_active();
    }

    public function start($request, $existing_session = false) {
        if (!$existing_session) {
            return;
        }
        $file = $this->session_file($this->session_key);
        $this->dbg('start(): about to check is_readable on '.$file);
        if (!is_readable($file)) {
            $this->active = false;
            $this->dbg('start(): file not readable, marking inactive');
            return;
        }
        // Locked read: Cypht fires several parallel AJAX calls on page
        // load, each reading/writing this same file. Without a lock, a
        // read racing an in-progress write returns a partial file, fails
        // to decrypt, and reports the session inactive.
        $fh = @fopen($file, 'rb');
        if ($fh === false) {
            $this->active = false;
            $this->dbg('start(): fopen failed');
            return;
        }
        $this->dbg('start(): fopen ok, requesting LOCK_SH');
        flock($fh, LOCK_SH);
        $this->dbg('start(): LOCK_SH acquired, reading');
        $raw = stream_get_contents($fh);
        flock($fh, LOCK_UN);
        fclose($fh);
        $this->dbg('start(): read '.strlen($raw).' bytes, unlocked');

        $data = $this->plaintext($raw);
        if (is_array($data)) {
            $this->data = $data;
            $this->active = true;
            $this->dbg('start(): decrypt OK, session active');
        } else {
            $this->active = false;
            $this->dbg('start(): decrypt FAILED (raw len '.strlen($raw).'), session inactive');
        }
    }

    public function get($name, $default = false, $user = false) {
        if ($user) {
            return (array_key_exists('user_data', $this->data) && array_key_exists($name, $this->data['user_data']))
                ? $this->data['user_data'][$name] : $default;
        }
        return array_key_exists($name, $this->data) ? $this->data[$name] : $default;
    }

    public function set($name, $value, $user = false) {
        if ($user) {
            $this->data['user_data'][$name] = $value;
        } else {
            $this->data[$name] = $value;
        }
    }

    public function del($name) {
        if (array_key_exists($name, $this->data)) {
            unset($this->data[$name]);
            return true;
        }
        return false;
    }

    public function end() {
        if ($this->active && !$this->session_closed) {
            $this->dbg('end(): persisting via write_locked()');
            $this->write_locked();
        }
        $this->active = false;
    }

    /**
     * Persists and closes the session early, before a slow operation
     * (e.g. testing IMAP/SMTP credentials) so the file lock isn't held.
     * Every stock Cypht session backend implements this; Hm_Session
     * itself does not provide a default, so leaving it unimplemented
     * here caused a fatal "Call to undefined method close_early()"
     * (uncaught Error, raw 503) in modules like nux's "Add an E-mail
     * Account".
     */
    public function close_early() {
        if ($this->active && !$this->session_closed) {
            $this->dbg('close_early(): persisting via write_locked()');
            $this->write_locked();
        }
        $this->session_closed = true;
    }

    private function write_locked() {
        // Exclusive lock, same reasoning as start() above.
        $fh = @fopen($this->session_file($this->session_key), 'cb');
        if ($fh !== false) {
            flock($fh, LOCK_EX);
            $this->dbg('write_locked(): LOCK_EX acquired, writing');
            ftruncate($fh, 0);
            rewind($fh);
            fwrite($fh, $this->ciphertext($this->data));
            fflush($fh);
            flock($fh, LOCK_UN);
            fclose($fh);
            $this->dbg('write_locked(): write complete, unlocked');
        } else {
            $this->dbg('write_locked(): fopen failed');
        }
    }

    public function destroy($request) {
        @unlink($this->session_file($this->session_key));
        $this->delete_cookie($request, $this->cname);
        $this->delete_cookie($request, 'hm_id');
        $this->active = false;
    }
}

class Custom_Auth extends Hm_Auth_DB {

    /**
     * @param string $user username (the Dolibarr login)
     * @param string $pass "{timestamp}.{hmac}" token from
     *                      CyphtSsoBridge::generateSsoLoginToken(), not a
     *                      real password
     * @return bool true if the token is a valid, fresh SSO assertion
     */
    public function check_credentials($user, $pass) {
        // See Custom_Session::session_dir() above re: avoiding env().
        $secret = Hm_Environment::get('SSO_SHARED_SECRET', '');
        if ($secret === '' || strpos($pass, '.') === false) {
            return false;
        }

        list($timestamp, $signature) = explode('.', $pass, 2);
        if (!ctype_digit($timestamp)) {
            return false;
        }

        // Anti-replay window: a captured token is only valid for a minute.
        if (abs(time() - (int) $timestamp) > 60) {
            return false;
        }

        $expected = hash_hmac('sha256', $user.'|'.$timestamp, $secret);

        return hash_equals($expected, $signature);
    }
}

/**
 * Replaces Hm_User_Config_File as the user-settings backend (via
 * USER_CONFIG_TYPE=custom:Custom_User_Config in .env).
 *
 * Hm_User_Config_File encrypts settings using the load()/save() "password"
 * as the literal key. Our SSO login passes a fresh per-request HMAC token
 * as that password, a different key every page load, so nothing saved
 * under one request's key could ever be decrypted the next. This class
 * ignores the key and stores plain JSON instead, same fix Tiki's
 * integration uses (Tiki_Hm_User_Config). Dolibarr's own auth already
 * gates access to this page, so there's no secret being protected anyway.
 *
 * @package modules
 * @subpackage site
 */
class Custom_User_Config extends Hm_Config {

    /** @var object Hm_Site_Config_File-like site config */
    private $site_config;

    /** @var string current username, set on load()/reload() */
    private $username;

    public function __construct($config) {
        $this->site_config = $config;
        $this->config = array_merge($this->config, $config->user_defaults);
    }

    private function get_path($username) {
        $dir = $this->site_config->get('user_settings_dir', false);
        $safe = preg_replace('/[^a-zA-Z0-9_.@-]/', '_', (string) $username);
        return rtrim((string) $dir, '/\\').'/'.$safe.'.json';
    }

    /**
     * @param string $username username
     * @param string $key intentionally ignored, see class doc comment
     */
    public function load($username, $key = null) {
        $this->username = $username;
        $source = $this->get_path($username);
        if (is_readable($source)) {
            $str_data = file_get_contents($source);
            if ($str_data) {
                $data = $this->decode($str_data);
                if (is_array($data)) {
                    $this->config = array_merge($this->config, $data);
                    $this->set_tz();
                }
            }
        }
    }

    public function reload($data, $username = false) {
        $this->username = $username;
        $this->config = $data;
        $this->set_tz();
    }

    /**
     * @param string $username username
     * @param string $key intentionally ignored, see class doc comment
     */
    public function save($username, $key = null) {
        $this->shuffle();
        $removed = $this->filter_servers();

        $dir = $this->site_config->get('user_settings_dir', false);
        if ($dir && !is_dir($dir)) {
            @mkdir($dir, 0700, true);
        }

        $fh = @fopen($this->get_path($username), 'cb');
        if ($fh !== false) {
            flock($fh, LOCK_EX);
            ftruncate($fh, 0);
            rewind($fh);
            fwrite($fh, json_encode($this->config));
            fflush($fh);
            flock($fh, LOCK_UN);
            fclose($fh);
            @chmod($this->get_path($username), 0600);
        }

        $this->restore_servers($removed);
    }
}
PHP;
	}

	/**
	 * Writes the generated auth override to Cypht's modules/site/lib.php.
	 * Must run on every build; Composer re-extracts this package directory
	 * whenever its locked version changes, wiping the file otherwise.
	 *
	 * @return bool
	 */
	public function writeSiteAuthOverride()
	{
		$path = $this->paths->getCyphtPath() . '/modules/site/lib.php';

		if (file_put_contents($path, $this->buildSiteAuthOverrideContent()) === false) {
			$this->error = 'Could not write ' . $path;
			return false;
		}

		return true;
	}

	/**
	 * Logs the given Dolibarr user into Cypht via its "functional login"
	 * SSO option (calls cypht_login() in-process, setting the
	 * hm_id/hm_session cookies). Must be called before any HTML output.
	 *
	 * Skips the login entirely if a live session already exists for this
	 * user (see hasLiveSsoSession()): cyphtWebmailindex.php calls this on
	 * every page load, and cypht_login() always resets the session data,
	 * which was silently discarding settings/servers that Cypht hadn't
	 * yet flagged for permanent storage. Requests made inside the iframe
	 * reuse the existing session cookie and never hit this path.
	 *
	 * @param string $login Dolibarr username to log into Cypht as
	 * @param string $cyphtUrl URL of the published Cypht app, need not be
	 *                          absolute already, see absolutizeUrl()
	 * @return bool true if Cypht accepted the SSO token, or a live session
	 *              already existed and was left alone
	 */
	public function performSsoLogin($login, $cyphtUrl)
	{
		if ($this->hasLiveSsoSession($login)) {
			return true;
		}

		$apiFile = $this->paths->getCyphtPath() . '/modules/api_login/api.php';
		if (!is_readable($apiFile)) {
			$this->error = 'modules/api_login/api.php not found; was the "api_login" module built into CYPHT_MODULES?';
			return false;
		}

		require_once $apiFile;

		$token = $this->generateSsoLoginToken($login);

		$ok = cypht_login($login, $token, $this->absolutizeUrl($cyphtUrl));
		if ($ok) {
			$this->rememberSsoSession($login);
		}

		return $ok;
	}

	/**
	 * Cookie recording which Dolibarr login the current Cypht session
	 * belongs to, separate from Cypht's own hm_session/hm_id.
	 *
	 * @return string
	 */
	private function ssoUserCookieName()
	{
		return 'cyphtwebmail_ssouser';
	}

	/**
	 * True if this browser already has a valid, still-on-disk Cypht
	 * session for $login: our own login-tracking cookie matches, Cypht's
	 * own hm_session cookie is set, and the session file it names still
	 * exists on disk.
	 *
	 * @param string $login
	 * @return bool
	 */
	private function hasLiveSsoSession($login)
	{
		if (empty($_COOKIE['hm_session']) || empty($_COOKIE['hm_id']) || empty($_COOKIE[$this->ssoUserCookieName()])) {
			return false;
		}

		if (!hash_equals((string) $login, (string) $_COOKIE[$this->ssoUserCookieName()])) {
			return false;
		}

		$sessionKey = preg_replace('/[^a-f0-9]/', '', (string) $_COOKIE['hm_session']);
		if ($sessionKey === '') {
			return false;
		}

		// Mirrors Custom_Session::session_file()'s naming convention.
		$sessionFile = $this->paths->getDataDir() . '/sso_sessions/' . $sessionKey . '.session';

		return is_readable($sessionFile);
	}

	/**
	 * Records which Dolibarr login the session cypht_login() just
	 * established, for the next request's hasLiveSsoSession() check.
	 * Session-lifetime cookie only; it authenticates nothing itself.
	 *
	 * @param string $login
	 * @return void
	 */
	private function rememberSsoSession($login)
	{
		$secure = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off');
		setcookie($this->ssoUserCookieName(), $login, array(
			'path' => '/',
			'secure' => $secure,
			'httponly' => true,
			'samesite' => 'Lax',
		));
	}

	/**
	 * cypht_login() needs a real absolute URL to work out the cookie
	 * domain; dol_buildpath() can return a host-relative one. Prepends
	 * the current request's scheme+host if $url doesn't have one already.
	 *
	 * @param string $url
	 * @return string
	 */
	private function absolutizeUrl($url)
	{
		if (preg_match('#^https?://#i', $url)) {
			return $url;
		}

		$scheme = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
		$host = !empty($_SERVER['HTTP_HOST']) ? $_SERVER['HTTP_HOST'] : 'localhost';
		$path = (substr($url, 0, 1) === '/') ? $url : '/' . $url;

		return $scheme . '://' . $host . $path;
	}
}
