<?php
/* Copyright (C) 2026  Camile   <camilevahviraki@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

require_once __DIR__ . '/../state/cyphtinstallstate.class.php';

/**
 * \file        class/sso/cyphtssobridge.class.php
 * \ingroup     cyphtWebmail
 * \brief       Dolibarr -> Cypht single sign-on bridge. Extracted out of
 *              CyphtManager, which had grown too large - see
 *              class/cyphtmanager.class.php for the facade that wires this
 *              together with its siblings.
 *
 * Owns the shared HMAC secret, the short-lived login tokens derived from
 * it, the generated modules/site/lib.php override (Custom_Auth/
 * Custom_Session) that makes Cypht trust those tokens instead of a real
 * IMAP/DB backend, and the actual in-process "functional login" call.
 */
class CyphtSsoBridge
{
	/**
	 * @var DoliDB
	 */
	public $db;

	/**
	 * @var string  Last error message, if any call returned false/failure.
	 */
	public $error = '';

	/**
	 * @var CyphtInstallState
	 */
	private $paths;

	/**
	 * @param DoliDB $db Database handler
	 * @param CyphtInstallState $paths
	 */
	public function __construct($db, CyphtInstallState $paths)
	{
		$this->db = $db;
		$this->paths = $paths;
	}

	/**
	 * Shared secret used to sign the short-lived SSO tokens passed to
	 * Cypht's cypht_login() in place of a real mailbox password (see
	 * generateSsoLoginToken() and buildSiteAuthOverrideContent()). Generated
	 * once and persisted in llx_const so it survives across requests and
	 * rebuilds; the same value is written into Cypht's own .env so
	 * Custom_Auth::check_credentials() can verify against it.
	 *
	 * @return string
	 */
	public function getOrCreateSsoSecret()
	{
		global $conf;

		$secret = getDolGlobalString('CYPHTWEBMAIL_SSO_SECRET', '');
		if ($secret !== '') {
			return $secret;
		}

		$secret = bin2hex(random_bytes(32));
		dolibarr_set_const($this->db, 'CYPHTWEBMAIL_SSO_SECRET', $secret, 'chaine', 0, '', $conf->entity);

		return $secret;
	}

	/**
	 * Build a short-lived, single-purpose token proving "this is really
	 * the current Dolibarr user", to hand to Cypht's cypht_login() as the
	 * password argument. It is never a real mailbox credential - just an
	 * HMAC of the username + timestamp, verified by Custom_Auth in
	 * modules/site/lib.php against the same SSO_SHARED_SECRET. The 60s
	 * window keeps a captured token from being replayable indefinitely.
	 *
	 * @param string $login Dolibarr username to embed in the token
	 * @return string
	 */
	public function generateSsoLoginToken($login)
	{
		$secret = $this->getOrCreateSsoSecret();
		$timestamp = time();
		$signature = hash_hmac('sha256', $login . '|' . $timestamp, $secret);

		return $timestamp . '.' . $signature;
	}

	/**
	 * Source for the generated modules/site/lib.php override that makes
	 * AUTH_TYPE=custom authenticate against our SSO token instead of a
	 * real IMAP/DB backend. Regenerated on every build (same pattern as
	 * CyphtVendorBridge::ensureCyphtVendorBridge()'s autoload shim) rather
	 * than hand-edited in vendor/, so a "composer update" never silently
	 * reverts it.
	 *
	 * @return string
	 */
	private function buildSiteAuthOverrideContent()
	{
		return <<<'PHP'
<?php

/**
 * Auto-generated by CyphtSsoBridge::buildSiteAuthOverrideContent() - do not
 * edit, this file is recreated on every build and any manual changes will be
 * lost. See class/sso/cyphtssobridge.class.php in the cyphtWebmail module
 * for the source of truth.
 *
 * Implements Dolibarr SSO: AUTH_TYPE=custom hands credential checking to
 * Custom_Auth below instead of a real IMAP/DB backend. The "password"
 * Custom_Auth ever sees is a short-lived HMAC token generated by
 * CyphtSsoBridge::generateSsoLoginToken() for the *currently logged in
 * Dolibarr user* - never a real mailbox password. Once logged in this
 * way, each user adds their actual IMAP mailbox separately via Cypht's
 * own Servers/Accounts settings page, exactly as Tiki's integration does.
 *
 * SESSION_TYPE=custom activates Custom_Session below, which stores
 * session data in its own encrypted files rather than PHP's native
 * session_start()/$_SESSION - required because performSsoLogin() runs
 * in the same PHP request as Dolibarr's own already-active session, and
 * Cypht's stock "PHP" session type would collide with it (documented at
 * https://github.com/cypht-org/cypht/wiki/Integration-Options).
 *
 * @package modules
 * @subpackage site
 */
class Custom_Session extends Hm_Session {

    use Hm_Session_Auth;

    /** @var bool true once a new login has established data to persist */
    private $existing = false;

    private function session_dir() {
        // Hm_Environment::get() reads array_merge($_ENV, $_SERVER) - real
        // per-request PHP superglobals. The global env() helper instead
        // does getenv() ?: default, which reads the *process-wide* OS
        // environment table populated via putenv() (Hm_Environment::load()
        // turns on Symfony Dotenv's usePutenv(true)). Symfony's own source
        // warns "putenv() is not thread safe" - and on Windows, Apache's
        // mpm_winnt runs one process with many threads sharing that same
        // process-wide table, so a concurrent request's putenv() unset/set
        // pair (Dotenv unsets a key before resetting it) can be observed
        // mid-flight by another thread's getenv() call. That's what was
        // causing this to intermittently fall back to sys_get_temp_dir()
        // instead of the real USER_SETTINGS_DIR on some requests - Cypht
        // then looked in the wrong directory, found no session file,
        // reported "inactive", and the client force-reloaded (see
        // public/site.js's logout()-on-!router_login_state). $_ENV itself
        // is set unconditionally by Dotenv::populate() regardless of the
        // putenv race (see vendor/symfony/dotenv/Dotenv.php), so reading
        // it directly via Hm_Environment::get() sidesteps the race.
        $base = dirname(rtrim(Hm_Environment::get('USER_SETTINGS_DIR', sys_get_temp_dir()), '/\\'));
        $dir = $base.'/sso_sessions';
        if (!is_dir($dir)) {
            @mkdir($dir, 0700, true);
        }
        return $dir;
    }

    private function session_file($key) {
        return $this->session_dir().'/'.preg_replace('/[^a-f0-9]/', '', (string) $key).'.session';
    }

    /**
     * Temporary diagnostic log, separate from Cypht's own debug system
     * (which is a black box from Dolibarr's side) - tracks this specific
     * request's method/URI plus each locking step, so a hung/crashed
     * request can be pinned to an exact line even though it returns a
     * raw 503 with no catchable PHP error at all.
     */
    private function dbg($line) {
        $uri = isset($_SERVER['REQUEST_URI']) ? $_SERVER['REQUEST_URI'] : '?';
        $method = isset($_SERVER['REQUEST_METHOD']) ? $_SERVER['REQUEST_METHOD'] : '?';
        // Written under the module root itself (not USER_SETTINGS_DIR,
        // which lives under Dolibarr's separate documents root) so this
        // is directly readable without needing anyone to relay it.
        $logPath = dirname(rtrim(APP_PATH, '/\\'), 3) . '/session_debug.log';
        @file_put_contents(
            $logPath,
            sprintf("[%s] pid=%d %s %s key=%s :: %s\n", date('H:i:s.u'), getmypid(), $method, $uri, substr((string) $this->session_key, 0, 8), $line),
            FILE_APPEND
        );
    }

    public function check($request, $user = false, $pass = false, $fingerprint = true) {
        if ($user !== false && $pass !== false) {
            if ($this->auth($user, $pass)) {
                $this->set_key($request);
                $this->session_key = bin2hex(random_bytes(16));
                $this->loaded = true;
                $this->data = [];
                $this->active = true;
                $this->dbg('NEW LOGIN established');
                if ($fingerprint) {
                    $this->set_fingerprint($request);
                } else {
                    $this->set('fingerprint', '');
                }
                $this->save_auth_detail();
                $this->just_started();
            } else {
                $this->dbg('auth() returned false for new login attempt');
            }
        } elseif (array_key_exists($this->cname, $request->cookie)) {
            $this->session_key = $request->cookie[$this->cname];
            $this->dbg('checking existing session cookie');
            $this->get_key($request);
            $this->existing = true;
            $this->start($request, true);
            if ($this->active) {
                $this->check_fingerprint($request);
                $this->dbg('active after fingerprint check = '.($this->active ? 'yes' : 'no'));
            }
        } else {
            $this->dbg('no cookie, no user/pass - anonymous request');
        }
        return $this->is_active();
    }

    public function start($request, $existing_session = false) {
        if (!$existing_session) {
            return;
        }
        $file = $this->session_file($this->session_key);
        $this->dbg('start(): about to check is_readable on '.$file);
        if (!is_readable($file)) {
            $this->active = false;
            $this->dbg('start(): file not readable, marking inactive');
            return;
        }
        // Locked read: Cypht's own JS fires several AJAX calls back to back
        // on page load, each a separate PHP request reading/writing this
        // same file. Without a lock, a read racing an in-progress write
        // (from another of those parallel requests) can return a partial
        // write, fail to decrypt, and report the session as inactive -
        // which is exactly what was causing repeated client-side reloads
        // (Cypht's JS force-reloads whenever it sees a logged-out response).
        $fh = @fopen($file, 'rb');
        if ($fh === false) {
            $this->active = false;
            $this->dbg('start(): fopen failed');
            return;
        }
        $this->dbg('start(): fopen ok, requesting LOCK_SH');
        flock($fh, LOCK_SH);
        $this->dbg('start(): LOCK_SH acquired, reading');
        $raw = stream_get_contents($fh);
        flock($fh, LOCK_UN);
        fclose($fh);
        $this->dbg('start(): read '.strlen($raw).' bytes, unlocked');

        $data = $this->plaintext($raw);
        if (is_array($data)) {
            $this->data = $data;
            $this->active = true;
            $this->dbg('start(): decrypt OK, session active');
        } else {
            $this->active = false;
            $this->dbg('start(): decrypt FAILED (raw len '.strlen($raw).'), session inactive');
        }
    }

    public function get($name, $default = false, $user = false) {
        if ($user) {
            return (array_key_exists('user_data', $this->data) && array_key_exists($name, $this->data['user_data']))
                ? $this->data['user_data'][$name] : $default;
        }
        return array_key_exists($name, $this->data) ? $this->data[$name] : $default;
    }

    public function set($name, $value, $user = false) {
        if ($user) {
            $this->data['user_data'][$name] = $value;
        } else {
            $this->data[$name] = $value;
        }
    }

    public function del($name) {
        if (array_key_exists($name, $this->data)) {
            unset($this->data[$name]);
            return true;
        }
        return false;
    }

    public function end() {
        if ($this->active) {
            $this->dbg('end(): requesting LOCK_EX to persist');
            // Locked write, same reasoning as start() above - exclusive
            // lock so a concurrent request's read can't observe a
            // half-written file.
            $fh = @fopen($this->session_file($this->session_key), 'cb');
            if ($fh !== false) {
                flock($fh, LOCK_EX);
                $this->dbg('end(): LOCK_EX acquired, writing');
                ftruncate($fh, 0);
                rewind($fh);
                fwrite($fh, $this->ciphertext($this->data));
                fflush($fh);
                flock($fh, LOCK_UN);
                fclose($fh);
                $this->dbg('end(): write complete, unlocked');
            } else {
                $this->dbg('end(): fopen failed');
            }
            $this->active = false;
        }
    }

    public function destroy($request) {
        @unlink($this->session_file($this->session_key));
        $this->delete_cookie($request, $this->cname);
        $this->delete_cookie($request, 'hm_id');
        $this->active = false;
    }
}

class Custom_Auth extends Hm_Auth_DB {

    /**
     * @param string $user username (the Dolibarr login)
     * @param string $pass "{timestamp}.{hmac}" token from
     *                      CyphtSsoBridge::generateSsoLoginToken(), not a
     *                      real password
     * @return bool true if the token is a valid, fresh SSO assertion
     */
    public function check_credentials($user, $pass) {
        // See the comment in Custom_Session::session_dir() above - the
        // global env() helper reads the process-wide (not thread-safe)
        // putenv() table, so it must be avoided here too.
        $secret = Hm_Environment::get('SSO_SHARED_SECRET', '');
        if ($secret === '' || strpos($pass, '.') === false) {
            return false;
        }

        list($timestamp, $signature) = explode('.', $pass, 2);
        if (!ctype_digit($timestamp)) {
            return false;
        }

        // Anti-replay window: a captured token is only valid for a minute.
        if (abs(time() - (int) $timestamp) > 60) {
            return false;
        }

        $expected = hash_hmac('sha256', $user.'|'.$timestamp, $secret);

        return hash_equals($expected, $signature);
    }
}
PHP;
	}

	/**
	 * Write the generated Custom_Auth/Custom_Session override to Cypht's
	 * modules/site/lib.php. Must run on every build, same reasoning as
	 * CyphtVendorBridge::ensureCyphtVendorBridge(): Composer fully
	 * re-extracts a package directory whenever its locked version changes,
	 * which would silently wipe this out.
	 *
	 * @return bool
	 */
	public function writeSiteAuthOverride()
	{
		$path = $this->paths->getCyphtPath() . '/modules/site/lib.php';

		if (file_put_contents($path, $this->buildSiteAuthOverrideContent()) === false) {
			$this->error = 'Could not write ' . $path;
			return false;
		}

		return true;
	}

	/**
	 * Log the given Dolibarr user into Cypht via its official "functional
	 * login" integration option (same-subdomain SSO, see
	 * https://github.com/cypht-org/cypht/wiki/API-Login) - calls
	 * cypht_login() directly in-process instead of round-tripping through
	 * an HTTP POST, setting the hm_id/hm_session cookies on the current
	 * response. Must be called before any HTML output.
	 *
	 * @param string $login Dolibarr username to log into Cypht as
	 * @param string $cyphtUrl URL of the published Cypht app - does not
	 *                          need to be absolute already, see below
	 * @return bool true if Cypht accepted the SSO token
	 */
	public function performSsoLogin($login, $cyphtUrl)
	{
		$apiFile = $this->paths->getCyphtPath() . '/modules/api_login/api.php';
		if (!is_readable($apiFile)) {
			$this->error = 'modules/api_login/api.php not found - was the "api_login" module built into CYPHT_MODULES?';
			return false;
		}

		require_once $apiFile;

		$token = $this->generateSsoLoginToken($login);

		return cypht_login($login, $token, $this->absolutizeUrl($cyphtUrl));
	}

	/**
	 * cypht_login()'s own url_parse() does parse_url($url)['scheme'/'host']
	 * with no fallback, to work out the cookie domain/secure flag - it
	 * needs a real absolute URL. dol_buildpath(..., 1) does not reliably
	 * return one (can come back host-relative depending on Dolibarr's own
	 * config), which is what caused "Undefined array key scheme/host"
	 * warnings here. Prepends the current request's own scheme+host if
	 * $url doesn't already have one; already-absolute URLs pass through.
	 *
	 * @param string $url
	 * @return string
	 */
	private function absolutizeUrl($url)
	{
		if (preg_match('#^https?://#i', $url)) {
			return $url;
		}

		$scheme = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
		$host = !empty($_SERVER['HTTP_HOST']) ? $_SERVER['HTTP_HOST'] : 'localhost';
		$path = (substr($url, 0, 1) === '/') ? $url : '/' . $url;

		return $scheme . '://' . $host . $path;
	}
}
