<?php
/* Copyright (C) 2026  Camile   <camilevahviraki@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

require_once __DIR__ . '/../state/cyphtinstallstate.class.php';

/**
 * \file        class/contacts/cyphtcontactsbridge.class.php
 */
class CyphtContactsBridge
{
	/**
	 * @var DoliDB
	 */
	public $db;

	/**
	 * @var string  Last error message, if any call returned false/failure.
	 */
	public $error = '';

	/**
	 * @var CyphtInstallState
	 */
	private $paths;

	/**
	 * Name of the generated Cypht module set. Must also appear in
	 */
	const MODULE_NAME = 'dolibarr_contacts';

	/**
	 * @param DoliDB $db Database handler
	 * @param CyphtInstallState $paths
	 */
	public function __construct($db, CyphtInstallState $paths)
	{
		$this->db = $db;
		$this->paths = $paths;
	}

	/**
	 * Absolute URL of the contact feed the generated module calls.
 *
	 * @return string
	 */
	public function getBridgeUrl()
	{
		return self::resolveBridgeUrl();
	}

	/**
	 * Same as getBridgeUrl(), as a static so CyphtEnvConfig can build the
 *
	 * @return string
	 */
	public static function resolveBridgeUrl()
	{
		$url = getDolGlobalString('CYPHTWEBMAIL_BRIDGE_URL', '');
		if ($url !== '') {
			// Escape hatch: on setups where Dolibarr's public URL is not
			return $url;
		}

		return dol_buildpath('/cyphtWebmail/bridge/contacts.php', 2);
	}

	/**
	 * Absolute path of the generated module set directory.
 *
	 * @return string
	 */
	public function getModulePath()
	{
		return $this->paths->getCyphtPath() . '/modules/' . self::MODULE_NAME;
	}

	/**
	 * Write the three files that make up the module set. Called from
 *
	 * @return bool
	 */
	public function writeModuleSet()
	{
		$dir = $this->getModulePath();

		if (!is_dir($dir) && !@mkdir($dir, 0755, true) && !is_dir($dir)) {
			$this->error = 'Could not create ' . $dir;
			return false;
		}

		$files = array(
			'setup.php'                 => $this->buildSetupContent(),
			'modules.php'               => $this->buildModulesContent(),
			'hm-dolibarr-contacts.php'  => $this->buildLibContent(),
		);

		foreach ($files as $name => $content) {
			if (file_put_contents($dir . '/' . $name, $content) === false) {
				$this->error = 'Could not write ' . $dir . '/' . $name;
				return false;
			}
		}

		return true;
	}

	/**
	 * setup.php: registers the loader handler on every page that consumes
 *
	 * @return string
	 */
	private function buildSetupContent()
	{
		return <<<'PHP'
<?php

/**
 * Auto-generated by CyphtContactsBridge::buildSetupContent(). Do not edit;
*
 * @package modules
 * @subpackage dolibarr_contacts
 */

if (!defined('DEBUG_MODE')) { die(); }

handler_source('dolibarr_contacts');
output_source('dolibarr_contacts');

/* Contacts page: the full list, grouped by third party. */
add_handler('contacts', 'load_dolibarr_contacts', true, 'dolibarr_contacts', 'load_contacts', 'after');

/* Compose: To/Cc/Bcc autocomplete reads the store via ajax_autocomplete_contact. */
add_handler('compose', 'load_dolibarr_contacts', true, 'dolibarr_contacts', 'load_contacts', 'after');
add_handler('ajax_autocomplete_contact', 'load_dolibarr_contacts', true, 'dolibarr_contacts', 'load_contacts', 'after');

/* Message view: lets find_message_contacts recognise senders we know about,
 * so a Dolibarr contact is not offered as "add to contacts". */
add_handler('ajax_imap_message_content', 'load_dolibarr_contacts', true, 'dolibarr_contacts', 'load_contacts', 'after');

/* vCard export includes the Dolibarr source too. */
add_handler('export_contact', 'load_dolibarr_contacts', true, 'dolibarr_contacts', 'process_export_contacts', 'before');

/* Empty/error state, rendered above the category tabs. Cypht's own
 * "No contacts in this category" is per tab and says nothing about where
 * contacts are supposed to come from. */
add_output('contacts', 'dolibarr_contacts_notice', true, 'dolibarr_contacts', 'contacts_content_start', 'after');

return array(
    'allowed_output' => array(
        'dolibarr_contact_count' => array(FILTER_VALIDATE_INT, false),
        'dolibarr_contacts_status' => array(FILTER_SANITIZE_FULL_SPECIAL_CHARS, false),
    ),
);
PHP;
	}

	/**
	 * modules.php: the single handler module. Kept small on purpose, the
 *
	 * @return string
	 */
	private function buildModulesContent()
	{
		return <<<'PHP'
<?php

/**
 * Auto-generated by CyphtContactsBridge::buildModulesContent(). Do not edit;
*
 * @package modules
 * @subpackage dolibarr_contacts
 */

if (!defined('DEBUG_MODE')) { die(); }

require_once APP_PATH.'modules/dolibarr_contacts/hm-dolibarr-contacts.php';

/**
 * Pulls Dolibarr third parties and contacts into the contact store.
*
 * @subpackage dolibarr_contacts/handler
 */
class Hm_Handler_load_dolibarr_contacts extends Hm_Handler_Module {

    public function process() {
        $store = $this->get('contact_store');
        if (!$store) {
            return;
        }

        $login = $this->session->get('username', false);
        if (!$login) {
            return;
        }

        $source = new Hm_Dolibarr_Contacts();
        if (!$source->configured()) {
            $this->out('dolibarr_contacts_status', 'unconfigured');
            return;
        }

        $status = 'ok';

        /* Every page load would otherwise mean an HTTP round trip to
         * Dolibarr, including each autocomplete keystroke. Cache the
         * fetched list in the Cypht session for a short TTL instead. */
        $cache = $this->session->get('dolibarr_contacts_cache', false);
        $stamp = (int) $this->session->get('dolibarr_contacts_cache_at', 0);

        if (!is_array($cache) || (time() - $stamp) > $source->ttl()) {
            $fetched = $source->fetch($login);
            if ($fetched === false) {
                /* Fetch failed. Keep serving the stale list rather than
                 * blanking the address book mid-session; the reason is on
                 * the debug log. */
                $status = 'error';
                if (!is_array($cache)) {
                    $cache = array();
                }
            } else {
                $cache = $fetched;
                $this->session->set('dolibarr_contacts_cache', $cache);
                $this->session->set('dolibarr_contacts_cache_at', time());
            }
        }

        if (count($cache) > 0) {
            $store->import($cache);
        }

        $this->append('contact_sources', 'dolibarr');
        $this->out('contact_store', $store, false);
        $this->out('dolibarr_contact_count', count($cache));
        $this->out('dolibarr_contacts_status', $status);
    }
}

/**
 * Explains an empty Dolibarr address book, above the category tabs.
*
 * @subpackage dolibarr_contacts/output
 */
class Hm_Output_dolibarr_contacts_notice extends Hm_Output_Module {

    protected function output() {
        $status = $this->get('dolibarr_contacts_status', 'unconfigured');
        $count = (int) $this->get('dolibarr_contact_count', 0);

        if ($status === 'ok' && $count > 0) {
            return ''; /* contacts loaded, nothing to explain */
        }

        if ($status === 'unconfigured') {
            return $this->notice(
                'warning',
                'Dolibarr contacts are not configured',
                'The webmail module could not find its link back to Dolibarr. '.
                'Re-run Generate in the module setup page to rebuild the configuration.',
                ''
            );
        }

        if ($status === 'error') {
            return $this->notice(
                'danger',
                'Could not reach Dolibarr',
                'Your Dolibarr contacts could not be loaded, so this list may be '.
                'incomplete. This is a connection problem, not an empty address book'.
                'Ask your administrator'.
                'to check the webmail module setup.',
                ''
            );
        }

        $newUrl = Hm_Environment::get('DOLIBARR_NEW_CONTACT_URL', '');

        return $this->notice(
            'info',
            'No Dolibarr contacts yet',
            'This address book is filled automatically from Dolibarr, so there is '.
            'nothing to add here directly. Create a contact in Dolibarr and it will '.
            'appear on this page. A contact needs an email address to show up, and '.
            'new entries can take up to five minutes to arrive.',
            $newUrl
        );
    }

    /**
     * @param string $level  Bootstrap alert suffix: info, warning, danger
     * @param string $title  Short headline
     * @param string $body   Explanatory sentence(s)
     * @param string $url    Optional Dolibarr URL for a call to action
     * @return string
     */
    private function notice($level, $title, $body, $url) {
        $res = '<div class="alert alert-'.$this->html_safe($level).' mx-3 my-2" role="alert">';
        $res .= '<h6 class="alert-heading mb-1">'.$this->html_safe($this->trans($title)).'</h6>';
        $res .= '<p class="mb-0 small">'.$this->html_safe($this->trans($body)).'</p>';

        if ($url !== '') {
            /* target="_top" because Cypht is embedded in an iframe inside
             * Dolibarr; without it the Dolibarr page would open nested
             * inside the webmail pane. */
            $res .= '<hr class="my-2">';
            $res .= '<a class="btn btn-sm btn-primary" target="_top" href="'.$this->html_safe($url).'">';
            $res .= '<i class="bi bi-person-plus-fill"></i> '.$this->html_safe($this->trans('Add a contact in Dolibarr'));
            $res .= '</a>';
        }

        $res .= '</div>';

        return $res;
    }
}
PHP;
	}

	/**
	 * hm-dolibarr-contacts.php: the HTTP client. Mirrors the token format
 *
	 * @return string
	 */
	private function buildLibContent()
	{
		return <<<'PHP'
<?php

/**
 * Auto-generated by CyphtContactsBridge::buildLibContent(). Do not edit;
*
 * @package modules
 * @subpackage dolibarr_contacts
 */

if (!defined('DEBUG_MODE')) { die(); }

/**
 * Read-only contact source backed by bridge/contacts.php in the Dolibarr
*
 * @subpackage dolibarr_contacts/lib
 */
class Hm_Dolibarr_Contacts {

    /** @var string Endpoint URL, injected via .env at build time */
    private $url;
    /** @var string Shared HMAC secret, same one the SSO login uses */
    private $secret;

    public function __construct() {
        /* Hm_Environment::get() rather than the env() helper, for the same
         * reason documented in the generated modules/site/lib.php. */
        $this->url = Hm_Environment::get('DOLIBARR_CONTACTS_URL', '');
        $this->secret = Hm_Environment::get('SSO_SHARED_SECRET', '');
    }

    /**
     * @return bool true if this source has everything it needs to run
     */
    public function configured() {
        return $this->url !== '' && $this->secret !== '';
    }

    /**
     * Seconds a fetched list stays good for. Dolibarr contacts change on a
    *
     * @return int
     */
    public function ttl() {
        return (int) Hm_Environment::get('DOLIBARR_CONTACTS_TTL', 300);
    }

    /**
     * Fetch the contact list for a Dolibarr login.
    *
     * @param string $login Dolibarr username, as put in the session by SSO
     * @return array|false Contact rows ready for Hm_Contact_Store::import(),
     */
    public function fetch($login) {
        if (!$this->configured()) {
            return false;
        }

        $timestamp = time();
        $signature = hash_hmac('sha256', $login.'|'.$timestamp.'|contacts', $this->secret);

        $url = $this->url.(strpos($this->url, '?') === false ? '?' : '&');
        $url .= http_build_query(array(
            'login' => $login,
            'token' => $timestamp.'.'.$signature,
        ));

        $body = $this->request($url);
        if ($body === false) {
            return false;
        }

        $data = json_decode($body, true);
        if (!is_array($data) || !array_key_exists('contacts', $data)) {
            Hm_Debug::add('dolibarr_contacts: unexpected response: '.substr($body, 0, 200));
            return false;
        }

        return $data['contacts'];
    }

    /**
     * @param string $url Fully built, signed request URL
     * @return string|false Response body, or false on transport failure
     */
    private function request($url) {
        $timeout = (int) Hm_Environment::get('DOLIBARR_CONTACTS_TIMEOUT', 5);

        if (function_exists('curl_init')) {
            $ch = curl_init($url);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
            curl_setopt($ch, CURLOPT_TIMEOUT, $timeout);
            curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, $timeout);
            /* The token is short lived but still a bearer credential, so
             * never follow a redirect that could carry it off-host. */
            curl_setopt($ch, CURLOPT_FOLLOWLOCATION, false);
            if (Hm_Environment::get('DOLIBARR_CONTACTS_INSECURE', 'false') === 'true') {
                /* For local XAMPP setups serving Dolibarr over a self-signed
                 * certificate. Off by default. */
                curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
                curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
            }
            $body = curl_exec($ch);
            $status = (int) curl_getinfo($ch, CURLINFO_HTTP_CODE);
            $err = curl_error($ch);
            curl_close($ch);

            if ($body === false || $status !== 200) {
                Hm_Debug::add('dolibarr_contacts: HTTP '.$status.' '.$err);
                return false;
            }
            return $body;
        }

        $context = stream_context_create(array('http' => array(
            'timeout' => $timeout,
            'follow_location' => 0,
            'ignore_errors' => true,
        )));
        $body = @file_get_contents($url, false, $context);
        if ($body === false) {
            Hm_Debug::add('dolibarr_contacts: request failed, no curl and file_get_contents returned false');
            return false;
        }
        return $body;
    }
}
PHP;
	}
}
